
package com.service.ws;

import java.util.List;

import javax.jws.WebService;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name="GestorLibros")
public interface GestorLibros {

	public List<Libro> listarLibros() throws Exception;
    
	public Libro getLibroById(String numSerie) throws Exception;
    
	public String addLibro(Libro libro) throws Exception;
    

}
